spring.main.web-application-type: none

# management.endpoints.web.exposure.include: health

# Additional server ports specified with Armeria configuration.
armeria:
  ports:
    - port: 8080
      protocols:
        - http
    - port: 8081
      protocols:
        - http
